### ISSUE TITLE
[v0.18.0] SIGSEGV after SIGINT (Ctrl+C)

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#1001]
`SIGSEGV` after `SIGINT` (Ctrl+C) in v0.18.0
```
(gdb) bt
#0  0x0000000000f5c317 in boost::multi_index::detail::bidir_node_iterator<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::index_node_base<steemit::chain::dynamic_global_property_object, boost::interprocess::allocator<steemit::chain::dynamic_global_property_object, boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0ul>, 0ul>, boost::interprocess::iset_index> > > > > boost::multi_index::detail::ordered_index<boost::multi_index::member<steemit::chain::dynamic_global_property_object, chainbase::oid<steemit::chain::dynamic_global_property_object>, &steemit::chain::dynamic_global_property_object::id>, std::less<chainbase::oid<steemit::chain::dynamic_global_property_object> >, boost::multi_index::detail::nth_layer<1, steemit::chain::dynamic_global_property_object, boost::multi_index::indexed_by<boost::multi_index::ordered_unique<boost::multi_index::tag<steemit::chain::by_id, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::member<steemit::chain::dynamic_global_property_object, chainbase::oid<steemit::chain::dynamic_global_property_object>, &steemit::chain::dynamic_global_property_object::id>, mpl_::na>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::interprocess::allocator<steemit::chain::dynamic_global_property_object, boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0ul>, 0ul>, boost::interprocess::iset_index> > >, boost::mpl::v_item<steemit::chain::by_id, boost::mpl::vector0<mpl_::na>, 0>, boost::multi_index::detail::ordered_unique_tag>::find<chainbase::oid<steemit::chain::dynamic_global_property_object> >(chainbase::oid<steemit::chain::dynamic_global_property_object> const&) const ()
#1  0x0000000000eda570 in steemit::chain::database::get_dynamic_global_properties() const ()
#2  0x0000000000edc11e in steemit::chain::database::get_slot_at_time(fc::time_point_sec) const ()
#3  0x0000000000e8fa64 in steemit::witness_plugin::witness_plugin::maybe_produce_block(fc::mutable_variant_object&) ()
#4  0x0000000000e9135f in steemit::witness_plugin::witness_plugin::block_production_loop() ()
#5  0x0000000000e92b7c in fc::detail::void_functor_run<steemit::witness_plugin::witness_plugin::schedule_production_loop()::{lambda()#1}>::run(void*, fc::detail::void_functor_run<steemit::witness_plugin::witness_plugin::schedule_production_loop()::{lambda()#1}>) ()
#6  0x00000000012c4094 in fc::task_base::run_impl() ()
#7  0x00000000012c1bad in fc::thread_d::process_tasks() ()
#8  0x00000000012c22b5 in fc::thread_d::start_process_tasks(long) ()
#9  0x000000000175d811 in make_fcontext ()
#10 0x7320616e6420616c in ?? ()
#11 0x0000000000000fb1 in ?? ()
#12 0x0000000003bc0e90 in ?? ()
#13 0x00007f9f417beb78 in main_arena () from /lib/x86_64-linux-gnu/libc.so.6
#14 0x0000000000000000 in ?? ()
```

**Comment by Gandalf-the-Grey** [comment]
Tested with current version, unable to reproduce anymore.
