### ISSUE TITLE
Error - double free or corruption

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#11]
First time I've seen this particular error:

    3134293ms th_a       database_api.cpp:190          ~database_api_impl   ] freeing database api 117726992
    3134296ms th_a       database_api.cpp:185          database_api_impl    ] creating database api 117730096
    3134296ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc":"2.0","method":"get_active_votes","params":["pharesim","ubuntu-14-04-miner-setup"],"id":0}
    *** Error in `steem/programs/steemd/steemd': double free or corruption (fasttop): 0x00007fffe8214b20 ***
    3134296ms th_a       database_api.cpp:190          ~database_api_impl   ] freeing database api 117730096

    Program received signal SIGABRT, Aborted.
    [Switching to Thread 0x7ffff5c2e700 (LWP 5282)]
    0x00007ffff69e8cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  0x00007ffff69e8cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    #1  0x00007ffff69ec0d8 in __GI_abort () at abort.c:89
    #2  0x00007ffff6a25394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff6b33b28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
    #3  0x00007ffff6a3166e in malloc_printerr (ptr=<optimized out>, str=0x7ffff6b33cf0 "double free or corruption (fasttop)", action=1) at malloc.c:4996
    #4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
    #5  0x0000000000af4c1e in boost::asio::detail::reactive_socket_send_op<boost::asio::detail::consuming_buffers<boost::asio::const_buffer, std::vector<boost::asio::const_buffer, std::allocator<boost::asio::const_buffer> > >, boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, std::vector<boost::asio::const_buffer, std::allocator<boost::asio::const_buffer> >, boost::asio::detail::transfer_all_t, websocketpp::transport::asio::custom_alloc_handler<std::function<void (boost::system::error_code const&, unsigned long)> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
    #6  0x0000000000aba4a0 in boost::asio::detail::task_io_service::run(boost::system::error_code&) ()
    #7  0x0000000000b5be1b in fc::asio::default_io_service_scope::default_io_service_scope()::{lambda()#1}::operator()() const ()
    #8  0x0000000000c6567a in thread_proxy ()
    #9  0x00007ffff7bc4182 in start_thread (arg=0x7ffff5c2e700) at pthread_create.c:312
    #10 0x00007ffff6aac47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Ubuntu 14.04 64-bit

**Comment by roadscape** [comment]
Happened again, running on latest (0.2.0)

    1171139ms th_a       database_api.cpp:189          database_api_impl    ] creating database api 143845744
    1171139ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc":"2.0","method":"get_witness_by_account","params":["anna"],"id":0}
    1171139ms th_a       database_api.cpp:194          ~database_api_impl   ] freeing database api 143845744

    Program received signal SIGABRT, Aborted.
    [Switching to Thread 0x7ffff3dd8700 (LWP 25220)]
    0x00007ffff655bcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  0x00007ffff655bcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    #1  0x00007ffff655f0d8 in __GI_abort () at abort.c:89
    #2  0x00007ffff6598394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff66a6b28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
    #3  0x00007ffff65a466e in malloc_printerr (ptr=<optimized out>, str=0x7ffff66a6cf0 "double free or corruption (fasttop)", action=1) at malloc.c:4996
    #4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
    #5  0x0000000000b0f69e in boost::asio::detail::reactive_socket_send_op<boost::asio::detail::consuming_buffers<boost::asio::const_buffer, std::vector<boost::asio::const_buffer, std::allocator<boost::asio::const_buffer> > >, boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, std::vector<boost::asio::const_buffer, std::allocator<boost::asio::const_buffer> >, boost::asio::detail::transfer_all_t, websocketpp::transport::asio::custom_alloc_handler<std::function<void (boost::system::error_code const&, unsigned long)> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
    #6  0x0000000000ae3110 in boost::asio::detail::task_io_service::run(boost::system::error_code&) ()
    #7  0x0000000000b4ba5b in fc::asio::default_io_service_scope::default_io_service_scope()::{lambda()#1}::operator()() const ()
    #8  0x0000000000c786ba in thread_proxy ()
    #9  0x00007ffff7bc4182 in start_thread (arg=0x7ffff3dd8700) at pthread_create.c:312
    #10 0x00007ffff661f47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by roadscape** [comment]
Haven't seen this error for approximately 8 weeks... closing.
