### ISSUE TITLE
I put this into command shell using windows and this I got an error

### ISSUE THREAD

**Issue by MELCHEZEDEK776** [steemit/steem#1106]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 / D e k Backspace l e t e Spacebar / V i c t o r Spacebar J o r d a n Enter
 n e t Spacebar u s e r Enter
 D e l Backspace Backspace Backspace Backspace / D e l e t e Enter
 N E T Shift+Spacebar U S E R Shift+Spacebar Enter
 N E T Shift+Spacebar U S E R Shift+Spacebar v i c t o Spacebar Enter
 N E T Shift+Spacebar U S E R Shift+Spacebar J e s u s C o i n s Enter
 N E T Shift+Spacebar U S E R Shift+Spacebar J E S U S C O I N S Enter
 c o m m e n t Spacebar - Spacebar H e l l o _ W o r l d Enter
 J E S U S C O I N S Spacebar / A D D Shift+Spacebar . Backspace / H e l l o Spacebar w o r l d Enter
 J e s u s C o i n s c Backspace Spacebar c o m m a n d Enter
 c o m m a n d Enter
 Ctrl+v Ctrl+v Ctrl+z

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -14793.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32& y)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by mvandeberg** [comment]
This does not appear to be related to Steem. Closing
