### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kenneth** [steemit/steem#2144]
what is wrong?

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/kenneth/Documents/BlockDev/steemit/steem/libraries/manifest/steem_manifest/build.py", line 2, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
CMake Error at libraries/manifest/CMakeLists.txt:59 (message):
  Could not get manifest dependencies


-- Configuring incomplete, errors occurred!
```

**Comment by mvandeberg** [comment]
In the OS X build instructions

```
brew install \
    autoconf \
    automake \
    cmake \
    git \
    boost160 \
    libtool \
    openssl \
    python3 \
    python3-jinja2
```

You're missing `python3-jinja2`

**Comment by mvandeberg** [comment]
Can you post the output of running cmake? I want to be sure it is linking to boost properly.

**Comment by kenneth** [comment]
@mvandeberg  boost version problem, but i don't know how to config.

```
➜  steem git:(master) ✗ cmake -DBOOST_ROOT=/usr/local/opt/boost@1.60
-- BUILD_STEEM_TESTNET: OFF
-- LOW_MEMORY_NODE: OFF
-- CHAINBASE_CHECK_LOCKING: ON
--    CONFIGURING TO CLEAR OLD VOTES FROM MEMORY
-- SKIP_BY_TX_ID: OFF
-- STEEM_STATIC_BUILD: OFF
-- Using custom FindBoost.cmake
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   coroutine
-- Configuring Steem on OS X
-- Configuring project fc located in: /Users/steemit/steem/libraries/fc
-- Configuring fc to build on Unix/Apple
-- Using custom FindBoost.cmake
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
--   coroutine
** websocketpp

=========== Used Build Configuration =============

-- ENABLE_CPP11        = ON
-- BUILD_EXAMPLES      = OFF
-- BUILD_TESTS         = OFF

-- WEBSOCKETPP_ROOT    = /Users/steemit/steem/libraries/fc/vendor/websocketpp
-- WEBSOCKETPP_BIN     = /Users/steemit/steem/libraries/fc/vendor/websocketpp/bin
-- WEBSOCKETPP_LIB     = /Users/steemit/steem/libraries/fc/vendor/websocketpp/lib
-- Install prefix      = /usr/local

-- WEBSOCKETPP_BOOST_LIBS        =
-- WEBSOCKETPP_PLATFORM_LIBS     =
-- WEBSOCKETPP_PLATFORM_TLS_LIBS =

-- OPENSSL_FOUND        = TRUE
-- OPENSSL_INCLUDE_DIR     = /opt/local/include
-- OPENSSL_LIBRARIES = /opt/local/lib/libssl.a;/opt/local/lib/libcrypto.a
-- OPENSSL_VERSION = 1.0.2n

-- Found Readline: /usr/lib/libreadline.dylib
-- zlib found
-- bzip2 found
-- LOG_LONG_API: ON
--
--      LOGGING LONG API CALLS
--           MAX  MS: 1000
--           WARN MS: 750
--
-- Finished fc module configuration...
-- Using custom FindBoost.cmake
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   chrono
--   unit_test_framework
--   locale
-- Configuring ChainBase on OS X
-- PLUGINS_DEPS: /Users/steemit/steem/libraries/manifest/../plugins/raw_block/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/auth_util/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/blockchain_statistics/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/witness/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/private_message/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/account_history/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/follow/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/account_statistics/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/debug_node/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/block_info/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/tags/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/delayed_node/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/account_by_key/plugin.json;/Users/steemit/steem/libraries/manifest/../plugins/market_history/plugin.json

-- MANIFEST_DEPS: /Users/steemit/steem/libraries/manifest/template_context/plugins.json;/Users/steemit/steem/libraries/manifest/templates/plugins/CMakeLists.txt.j2;/Users/steemit/steem/libraries/manifest/templates/plugins/plugins.cpp;/Users/steemit/steem/libraries/manifest/templates/plugins/mf_plugins.cpp.j2;/Users/steemit/steem/libraries/manifest/templates/plugins/include/steemit/manifest/plugins.hpp

-- MANIFEST_OUTPUTS: /Users/steemit/steem/libraries/manifest/gensrc/plugins/CMakeLists.txt;/Users/steemit/steem/libraries/manifest/gensrc/plugins/plugins.cpp;/Users/steemit/steem/libraries/manifest/gensrc/plugins/mf_plugins.cpp;/Users/steemit/steem/libraries/manifest/gensrc/plugins/include/steemit/manifest/plugins.hpp

--

             CONFIGURED FOR STEEM NETWORK


--

             CONFIGURED FOR FULL NODE


-- Configuring done
-- Generating done
-- Build files have been written to: /Users/steemit/steem
```

**Comment by mvandeberg** [comment]
It looks like it is configuring properly. I have never ran into this problem building on OS X.

What version of OS X are you on? It might be a problem building on a new version and my old environment has carried over into newer versions of OS X. Or it might be a problem with an old version that we no longer build on.

**Comment by kenneth** [comment]
@mvandeberg my osx 10.13.3, i think the main problem is the fc libuary use boost_1.51,but my system boost is install use homebrew have 2 version boost 1.66 and boost@1.60 , cmake set the boost path ,but the program still run to boost_1.51 ,it let me so frustration。

**Comment by egonson** [comment]
I have same problem

In file included from /Users/egon/Workspace/steem/libraries/fc/src/interprocess/process.cpp:7:
In file included from /Users/egon/Workspace/steem/libraries/fc/vendor/boost_1.51/include/boost/process/all.hpp:24:
In file included from /Users/egon/Workspace/steem/libraries/fc/vendor/boost_1.51/include/boost/process/context.hpp:35:
/Users/egon/Workspace/steem/libraries/fc/vendor/boost_1.51/include/boost/process/self.hpp:48:19: error: declaration of 'environ' has a different
      language linkage
    extern char **environ;

I am using osx 10.13.5, boost16.0
