### ISSUE TITLE
Api breakage for market related operations? (json field name change? plus  Could not find method get_api_by_name)

### ISSUE THREAD

**Issue by muksihs** [steemit/steem#2159]
The json response for market orders is using a different field name for price suddenly? (price => order_price)

(error message is from steemj, but reflects error caused by unexpected json response format change)
```
not marked as ignorable (3 known properties: "price", "steem", "sbd"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: java.lang.Object[0]->eu.bittrade.libs.steemj.apis.market.history.model.OrderBook["bids"]->java.util.ArrayList[0]->eu.bittrade.libs.steemj.apis.market.history.model.Order["order_price"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3738)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3676)
        at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.handleResult(JsonRPCResponse.java:164)
        at eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:124)
        at eu.bittrade.libs.steemj.apis.market.history.MarketHistoryApi.getOrderBook(MarketHistoryApi.java:146)
        at eu.bittrade.libs.steemj.SteemJ.getOrderBookUsingMarketApi(SteemJ.java:2125)
        at com.muksihs.steembot.algo.SimpleScalpForSteem.updateOrderPriceBook(SimpleScalpForSteem.java:810)
        at com.muksihs.steembot.algo.SimpleScalpForSteem.execute(SimpleScalpForSteem.java:534)
        at com.muksihs.steembot.TradingBot.doTrades(TradingBot.java:100)
        at com.muksihs.steembot.TradingBot.execute(TradingBot.java:51)
        at com.muksihs.steembot.TradingBot.run(TradingBot.java:239)
        at java.lang.Thread.run(Thread.java:748)
```

and also suddenly getting: "method_itr != api_itr->second.end(): Could not find method get_api_by_name"

```
eu.bittrade.libs.steemj.exceptions.SteemResponseException: Assert Exception:method_itr != api_itr->second.end(): Could not find method get_api_by_name
        at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.createThrowable(JsonRPCResponse.java:306)
        at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.handleError(JsonRPCResponse.java:273)
        at eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:120)
        at eu.bittrade.libs.steemj.apis.login.LoginApi.getApiByName(LoginApi.java:107)
        at eu.bittrade.libs.steemj.SteemJ.getApiByName(SteemJ.java:319)
        at eu.bittrade.libs.steemj.SteemJ.<init>(SteemJ.java:157)
```

**Comment by mvandeberg** [comment]
We recently deployed a fairly large update to `api.steemit.com`.

The changes can be read [here](https://github.com/steemit/steem/releases/tag/v0.19.4rc1).

Please read through the release notes.

The quick thing you need to know. `get_api_by_name` is no longer needed. Just call the API name and it will work.

`database_api.get_order_book` has always returned the price as `order_price`. Is it possible there is some other underlying error?

**Comment by muksihs** [comment]
As the stable release steemj library is currently non-operational because
"get_api_by_name" is no longer supported, I'm not sure about how to debug
the json field name change error. The corresponding java pojo and operation
refer to the market history api plugin, would this be part of the
database_api.* set or a different set? There are two getOrderBook api calls
in SteemJ, one says getOrderBookUsingMarketApi and the other says
getOrderBookUsingDatabaseApi, I am using "getOrderBookUsingMarketApi" which
I think is using a different API endpoint and expecting a different api
response format than what it is receiving now.


   - GROWLr: LeatherDogMuksihs
   - RECON: https://www.recon.com/view_profile.aspx?id=1442667
   - FACEBOOK: https://www.facebook.com/muksihs


On Fri, Feb 23, 2018 at 7:25 PM, Michael Vandeberg <notifications@github.com

**Comment by mvandeberg** [comment]
Can you link to the library? It is not one I am familiar with.

**Comment by mvandeberg** [comment]
If it is the market history api plugin, then I would expect it is using the version in `market_history_api`. The order book was in two places. I was not aware that projects were using that version over the `database_api` version. We had to choose one to serve in a backwards compatible manner and we chose the one that breaks this particular library. As it is not a Steemit, Inc. maintained library, I would contact the creator of that library with the described problem.

**Comment by muksihs** [comment]
links:

https://github.com/marvin-we/steem-java-api-wrapper

https://steemit.com/@steemj


   - GROWLr: LeatherDogMuksihs
   - RECON: https://www.recon.com/view_profile.aspx?id=1442667
   - FACEBOOK: https://www.facebook.com/muksihs


On Fri, Feb 23, 2018 at 8:08 PM, Michael Vandeberg <notifications@github.com

**Comment by muksihs** [comment]
So, the two different API end points are identical in response then? (I was
rather confused by there being two getorderbook calls)


   - GROWLr: LeatherDogMuksihs
   - RECON: https://www.recon.com/view_profile.aspx?id=1442667
   - FACEBOOK: https://www.facebook.com/muksihs


On Fri, Feb 23, 2018 at 8:16 PM, Michael Vandeberg <notifications@github.com

**Comment by sneak** [comment]
Thanks for the bug report, @muksihs, and thanks for notifying the library maintainer.
