### ISSUE TITLE
Issue when running npm start on OSX

### ISSUE THREAD

**Issue by aaroncox** [steemit/steem#224]
I'm currently running into an issue setting up a local development environment (OSX). I have everything working setup, but once started, I'm receiving the following errors and the JS files are missing in the local server.

From the sounds of the error, it looks like babel isn't working correctly? Can anyone shed any insights into why this is occurring?

```
> clout@1.0.0 start /Users/acox/projects/steemit.com
> babel-node ./webpack/dev-server.js

`webpack-dev-server` listening on port 3001
`webpack-stats.json` updated
./app/components/pages/Search.jsx
Module build failed: SyntaxError: /Users/acox/projects/steemit.com/app/components/pages/Search.jsx: Unexpected token (9:22)
   7 |         {/*<iframe style={{width: "100%", height: "100vh", maxWidth: "800px"}} frameBorder="0" src="/static/search.html">
   8 |             </iframe>*/}
>  9 |             <div>Site search if temporary unavailable. Sorry for the inconvenience.</div>
     |                       ^
  10 |         );
  11 |     }
  12 | }
    at Parser.pp.raise (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.expect (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/util.js:83:33)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:582:12)
    at Parser.pp.parseExprAtom (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:481:19)
    at Parser.parseExprAtom (/Users/acox/projects/steemit.com/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
    at Parser.pp.parseExprSubscripts (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:277:19)
    at Parser.pp.parseMaybeUnary (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:257:19)
    at Parser.pp.parseExprOps (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:188:19)
    at Parser.pp.parseMaybeConditional (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:165:19)
 @ ./app/RootRoute.js 45:22-60
webpack built 0affcdca81842f9837df in 32328ms
Time: 32328ms
                               Asset     Size  Chunks       Chunk Names
1fe805bf4c773eeb3bebf1e78e6736ed.jpg  15.2 kB
0ee064e31a180b13aca01418634567a1.png  4.74 kB
                           vendor.js  25.8 kB       0       vendor
         app.0affcdca81842f9837df.js  7.03 MB    1, 0       app
                       vendor.js.map  26.7 kB       0       vendor
     app.0affcdca81842f9837df.js.map  7.99 MB    1, 0       app

ERROR in ./app/components/pages/Search.jsx
Module build failed: SyntaxError: /Users/acox/projects/steemit.com/app/components/pages/Search.jsx: Unexpected token (9:22)
   7 |         {/*<iframe style={{width: "100%", height: "100vh", maxWidth: "800px"}} frameBorder="0" src="/static/search.html">
   8 |             </iframe>*/}
>  9 |             <div>Site search if temporary unavailable. Sorry for the inconvenience.</div>
     |                       ^
  10 |         );
  11 |     }
  12 | }
    at Parser.pp.raise (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.expect (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/util.js:83:33)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:582:12)
    at Parser.pp.parseExprAtom (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:481:19)
    at Parser.parseExprAtom (/Users/acox/projects/steemit.com/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
    at Parser.pp.parseExprSubscripts (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:277:19)
    at Parser.pp.parseMaybeUnary (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:257:19)
    at Parser.pp.parseExprOps (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:188:19)
    at Parser.pp.parseMaybeConditional (/Users/acox/projects/steemit.com/node_modules/babylon/lib/parser/expression.js:165:19)
 @ ./app/RootRoute.js 45:22-60
webpack: bundle is now VALID.
```

**Comment by aaroncox** [comment]
Bah! I'm a smart one today, opened it in the wrong repo. Moving to the proper place...
