### ISSUE TITLE
Cannot find module '@steemit/rpc-auth'

### ISSUE THREAD

**Issue by DoctorLai** [steemit/steem#3042]
I cannot get `npm test` to work... even i did a `npm install steemit/rpc-auth`

```
npm test

> @steemit/steem-js@0.7.2 test /var/www/steem-js
> eslint --quiet src test; mocha -t 40000 --require babel-polyfill --require babel-register

module.js:550
    throw err;
    ^

Error: Cannot find module '@steemit/rpc-auth'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/steem-js/src/api/index.js:18:1)
    at Module._compile (module.js:653:30)
    at loader (/root/.nvm/versions/node/v8.12.0/lib/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/root/.nvm/versions/node/v8.12.0/lib/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/steem-js/src/index.js:1:13)
    at Module._compile (module.js:653:30)
    at loader (/root/.nvm/versions/node/v8.12.0/lib/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/root/.nvm/versions/node/v8.12.0/lib/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/steem-js/test/api.test.js:5:1)
    at Module._compile (module.js:653:30)
    at loader (/root/.nvm/versions/node/v8.12.0/lib/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/root/.nvm/versions/node/v8.12.0/lib/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /root/.nvm/versions/node/v8.12.0/lib/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/root/.nvm/versions/node/v8.12.0/lib/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/root/.nvm/versions/node/v8.12.0/lib/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/root/.nvm/versions/node/v8.12.0/lib/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! Test failed.  See above for more details.
```

**Comment by DoctorLai** [comment]
sorry, wrong repro. have copied this over to steem-js
