### ISSUE TITLE
Community - TESTNET:  RPCError: Unable to acquire database lock

### ISSUE THREAD

**Issue by yuriks2000** [steemit/steem#3067]
Using condenser pointing to https://testnet.steemitdev.com

When testing in the browser from https://steemtest.com getting Server error and when I check condenser logs I am getting the following error:

Error: 
<-- GET / 52944e73a9a22516bb28474228
State/store error:  RPCError: Unable to acquire database lock RPCError: Unable to acquire database lock
    at new RPCError (/home/user/condenser/node_modules/@steemit/steem-js/lib/api/transports/http.js:39:106)
    at /home/user/condenser/node_modules/@steemit/steem-js/lib/api/transports/http.js:74:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  --> GET / 500 1,217ms 3.93kB 52944e73a9a22516bb28474228
StatsLoggerClient call:  { '0': 'request.appRender_ms', '1': 1214.862982 }
StatsLoggerClient call:  { '0': 'request.total_ms', '1': 1227.466419 }

Sometimes when I refresh the page in the browser it works and no error, but most of the times it gives Server error (Page with a robot).

Under the mainnet, this error does not appear.

**Comment by bobinson** [comment]
Note that this issue appears when using tinman too and a bug has been [reported](https://github.com/steemit/tinman/issues/153) with  temporary workaround   to fix from Tinman's PoV. Root cause of the error will help to find a permanent fix.

**Comment by nikita-ng** [comment]
Facing same issue. @yuriks2000 Have you got any solution?
