### ISSUE TITLE
Error - free(): invalid size

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#71]
The first crash in 10 days, since building from develop @ 4ef97bee.

    902681ms th_a       database_api.cpp:194          database_api_impl    ] creating database api 265530496
    902682ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc":"2.0","method":"get_account_count","params":[],"id":0}
    902682ms th_a       database_api.cpp:199          ~database_api_impl   ] freeing database api 265530496
    *** Error in `steem/programs/steemd/steemd': free(): invalid size: 0x00007fffec220870 ***

    Program received signal SIGABRT, Aborted.
    [Switching to Thread 0x7ffff1d54700 (LWP 26112)]
    0x00007ffff655bcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  0x00007ffff655bcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    #1  0x00007ffff655f0d8 in __GI_abort () at abort.c:89
    #2  0x00007ffff6598394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff66a6b28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
    #3  0x00007ffff65a466e in malloc_printerr (ptr=<optimized out>, str=0x7ffff66a2c31 "free(): invalid size", action=1) at malloc.c:4996
    #4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
    #5  0x0000000000b30c95 in std::_Sp_counted_ptr_inplace<fc::detail::log_context_impl, std::allocator<fc::detail::log_context_impl>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
    #6  0x0000000000b30df1 in std::_Sp_counted_ptr_inplace<fc::detail::log_message_impl, std::allocator<fc::detail::log_message_impl>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
    #7  0x0000000000803819 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
    #8  0x0000000000a9582d in std::vector<fc::log_message, std::allocator<fc::log_message> >::operator=(std::vector<fc::log_message, std::allocator<fc::log_message> > const&) ()
    #9  0x0000000000a90f2c in fc::exception::operator=(fc::exception const&) ()
    #10 0x0000000000cdb95e in graphene::net::detail::peer_database_impl::update_entry(graphene::net::potential_peer_record const&) ()
    #11 0x0000000000c762c0 in graphene::net::detail::node_impl::connect_to_task(std::shared_ptr<graphene::net::peer_connection>, fc::ip::endpoint const&) ()
    #12 0x0000000000c76a72 in fc::detail::void_functor_run<graphene::net::detail::node_impl::initiate_connect_to(std::shared_ptr<graphene::net::peer_connection> const&)::{lambda()#1}>::run(void*, fc::detail::void_functor_run<graphene::net::detail::node_impl::initiate_connect_to(std::shared_ptr<graphene::net::peer_connection> const&)::{lambda()#1}>) ()
    #13 0x0000000000aa5fa3 in fc::task_base::run_impl() ()
    #14 0x0000000000aa3f7e in fc::thread_d::process_tasks() ()
    #15 0x0000000000aa4206 in fc::thread_d::start_process_tasks(long) ()
    #16 0x0000000000d4f0c1 in make_fcontext ()
    #17 0x0000000000000000 in ?? ()

**Comment by roadscape** [comment]
Haven't seen this error for approximately 4 weeks... closing.
